server:
  port: 8085
spring:
  datasource:
    url: jdbc:h2:mem:PlayerLovedGamesDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect